# Generated by Django 2.2.3 on 2019-07-31 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Category name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created in')),
            ],
            options={
                'verbose_name': 'Category Detail',
                'verbose_name_plural': 'Categories Detail',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Contact name')),
                ('phone', models.PositiveIntegerField(verbose_name='Phone number')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Category', verbose_name='Belongs to Category')),
            ],
            options={
                'verbose_name': 'Contact Detail',
                'verbose_name_plural': 'Contacts Detail',
            },
        ),
    ]
