# Generated by Django 2.2.3 on 2019-08-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190801_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
