# Generated by Django 2.2.3 on 2019-08-04 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20190804_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator('^\\d{9,10}$')], verbose_name='Phone number'),
        ),
    ]
