# Generated by Django 2.2.3 on 2019-08-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20190804_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Category name'),
        ),
    ]
