# Generated by Django 2.2.3 on 2019-08-05 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20190805_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_on'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_registered'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='messagehistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='date_registred',
            new_name='date_registered',
        ),
    ]
